script mop_magmafiend (void)
{
	if (CheckInventory("Attack1"))
	{
		TakeInventory("Attack1", 1);
		GiveInventory("Attack2", 1);
		print(s:"\cflunge");
		terminate;
	}
	
	if (CheckInventory("Attack2"))
	{
		TakeInventory("Attack2", 1);
		GiveInventory("Attack3", 1);
		print(s:"\cifire breath");
		terminate;
	}
	
	if (CheckInventory("Attack3"))
	{
		TakeInventory("Attack3", 1);
		GiveInventory("Attack1", 1);
		print(s:"\cimagma ball");
		terminate;
	}
}

script mop_helemental (void)
{
	if (CheckInventory("Attack1"))
	{
		TakeInventory("Attack1", 1);
		GiveInventory("Attack2", 1);
		print(s:"\cgseeking");
		terminate;
	}
	
	if (CheckInventory("Attack2"))
	{
		TakeInventory("Attack2", 1);
		GiveInventory("Attack3", 1);
		print(s:"\cgcomet");
		terminate;
	}
	
	if (CheckInventory("Attack3"))
	{
		TakeInventory("Attack3", 1);
		GiveInventory("Attack1", 1);
		print(s:"\cgnormal");
		terminate;
	}
}

script mop_hellarchon (void)
{
	if (CheckInventory("Attack1"))
	{
		TakeInventory("Attack1", 1);
		GiveInventory("Attack2", 1);
		print(s:"\cgburst ball");
		terminate;
	}
	
	if (CheckInventory("Attack2"))
	{
		TakeInventory("Attack2", 1);
		GiveInventory("Attack3", 1);
		print(s:"\cgcomet");
		terminate;
	}
	
	if (CheckInventory("Attack3"))
	{
		TakeInventory("Attack3", 1);
		GiveInventory("Attack1", 1);
		print(s:"\cgnormal");
		terminate;
	}
}

script mop_pyrodemon (void)
{
	if (CheckInventory("Attack1"))
	{
		TakeInventory("Attack1", 1);
		GiveInventory("Attack2", 1);
		print(s:"\cicomet");
		terminate;
	}
	
	if (CheckInventory("Attack2"))
	{
		TakeInventory("Attack2", 1);
		GiveInventory("Attack3", 1);
		print(s:"\cifloor hugger");
		terminate;
	}
	
	if (CheckInventory("Attack3"))
	{
		TakeInventory("Attack3", 1);
		GiveInventory("Attack1", 1);
		print(s:"\cinormal");
		terminate;
	}
}