script mop_magmafiend (void)
{
	if (CheckInventory("Attack1"))
	{
		TakeInventory("Attack1", 1);
		GiveInventory("Attack2", 1);
		print(s:"\cflunge");
		terminate;
	}
	
	if (CheckInventory("Attack2"))
	{
		TakeInventory("Attack2", 1);
		GiveInventory("Attack3", 1);
		print(s:"\cifire breath");
		terminate;
	}
	
	if (CheckInventory("Attack3"))
	{
		TakeInventory("Attack3", 1);
		GiveInventory("Attack1", 1);
		print(s:"\cimagma ball");
		terminate;
	}
}