#library "mop"
#include "zcommon.acs"

#define mop_possess 800
#define mop_enter 801
#define mop_respawn 802
#define mop_possessed_hud 803
#define mop_respawn_puppetmaster 804
#define mop_evade 805
#define mop_autoconfig 806
#define mop_phaseimp 807
#define mop_magmafiend 808
#define mop_helemental 809

#define MAX_PLAYERS 64
#define INT_MAX 2147483647
#define TEMPTID 8080

#include "monsters.acs"
#include "game.acs"
#include "attacks.acs"
#include "evade.acs"
#include "possess.acs"
